Caiopo master
caravelahc/cagrex pull request #14
Opened 2020-10-31 20:16 UTC by GabrielSimonetto

This was mosly @caiopo work on #11 

```
    Fix poetry install warning
    Add a config file to provide credentials to authenticated tests
    Cleanup dead code
    Fix tests
```

I somehow managed to erase all of his commits on his own fork, and I have no idea how, but locally they were still in my machine

2021-04-06 03:29 UTC, aBARICHELLO requested changes

2021-04-06 03:29 UTC, aBARICHELLO commented on tests/course_test.py
> +@pytest.mark.skip(reason="Still needs work")
termina ou remove esse teste aqui

2021-04-07 17:19 UTC, GabrielSimonetto commented on tests/course_test.py
> +@pytest.mark.skip(reason="Still needs work")
removi e criei uma issue pra refazer depois

2021-04-20 00:54 UTC, abarichello approved these changes
🔝

2021-04-20 00:54 UTC, merged